"""empty message

Revision ID: e10077e99dd5
Revises: 
Create Date: 2018-03-30 12:48:19.637646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10077e99dd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('rType', sa.String(length=32), nullable=True),
    sa.Column('rDescription', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_email'), 'retailer', ['email'], unique=True)
    op.create_index(op.f('ix_retailer_name'), 'retailer', ['name'], unique=True)
    op.create_table('retailer_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailerID', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('contactNumber', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['retailerID'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailerID', sa.Integer(), nullable=True),
    sa.Column('addressID', sa.Integer(), nullable=True),
    sa.Column('couponTitle', sa.String(length=64), nullable=True),
    sa.Column('currentPrice', sa.Float(), nullable=True),
    sa.Column('discountType', sa.String(length=32), nullable=True),
    sa.Column('offValue', sa.Float(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['addressID'], ['retailer_address.id'], ),
    sa.ForeignKeyConstraint(['retailerID'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon')
    op.drop_table('retailer_address')
    op.drop_index(op.f('ix_retailer_name'), table_name='retailer')
    op.drop_index(op.f('ix_retailer_email'), table_name='retailer')
    op.drop_table('retailer')
    # ### end Alembic commands ###
